# Dockerfile-master
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y curl && \
    curl -L https://bootstrap.saltstack.com -o install_salt.sh && \
    sh install_salt.sh -d -M -X onedir %%VERSION%%

WORKDIR /opt/saltstack/salt

CMD salt-master -l info & salt-api -l info
