# Dockerfile-minion
FROM ubuntu:22.04

WORKDIR /opt/saltstack/salt
ENV LOG_LEVEL=info

RUN apt-get update && apt-get install -y curl && \
    curl -L https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh -o bootstrap-salt.sh && \
    sh bootstrap-salt.sh -d -X onedir %%VERSION%%

CMD salt-minion -l $LOG_LEVEL
