# Dockerfile-minion
FROM ubuntu:22.04

WORKDIR /opt/saltstack/salt
ENV LOG_LEVEL=info
EXPOSE 4505 4506 8080

RUN apt-get update && apt-get install -y curl && \
    curl -L https://bootstrap.saltstack.com -o install_salt.sh && \
    sh install_salt.sh -d -X onedir %%VERSION%%

CMD salt-minion -l $LOG_LEVEL
