name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [master, minion]
        version: [3006.7, 3007.1]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy Dockerfile and substitute version number
      run: |
        cp Dockerfile-${{ matrix.image }} Dockerfile-${{ matrix.image }}-${{ matrix.version }}
        sed -i "s/%%VERSION%%/${{ matrix.version }}/g" Dockerfile-${{ matrix.image }}-${{ matrix.version }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile-${{ matrix.image }}-${{ matrix.version }}
        push: true
        tags: ghcr.io/foorack/saltdocker:${{ matrix.image }}-${{ matrix.version }}
